# IAM
IAM_USER=jellyfin
IAM_GROUP=jellyfin

IAM_USER_GROUPS_jellyfin=jellyfin,media
IAM_GROUP_USERS_jellyfin=jellyfin,root

# Dirs
DIR_SETUP=config|jellyfin|jellyfin
DIR_SETUP=cache|jellyfin|jellyfin
