# IAM
IAM_USER=adguardhome
IAM_GROUP=adguardhome

IAM_USER_GROUPS_adguardhome=adguardhome
IAM_GROUP_USERS_adguardhome=adguardhome,root

# Dirs
DIR_SETUP=work|adguardhome|adguardhome
DIR_SETUP=conf|adguardhome|adguardhome|750
