# IAM
IAM_USER=filebrowser
IAM_GROUP=filebrowser

IAM_USER_GROUPS_filebrowser=filebrowser,storage,media
IAM_GROUP_USERS_filebrowser=filebrowser,root

# Dirs
DIR_SETUP=data|filebrowser|filebrowser
DIR_SETUP=files|filebrowser|filebrowser

#ENV
ENV_FILEBROWSER_CONFIG=data/config.yaml